/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    'roles': RouteRecordInfo<
      'roles',
      '/settings/roles',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'roles-detail': RouteRecordInfo<
      'roles-detail',
      '/settings/roles/:roleId',
      { roleId: ParamValue<true> },
      { roleId: ParamValue<false> },
      | 'roles-permissions'
      | 'roles-update'
    >,
    'roles-update': RouteRecordInfo<
      'roles-update',
      '/settings/roles/:roleId/edit',
      { roleId: ParamValue<true> },
      { roleId: ParamValue<false> },
      | never
    >,
    'roles-permissions': RouteRecordInfo<
      'roles-permissions',
      '/settings/roles/:roleId/permissions',
      { roleId: ParamValue<true> },
      { roleId: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/routes/settings/roles/index.route.vue': {
      routes:
        | 'roles'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/settings/roles/[roleId]/_parent.route.vue': {
      routes:
        | 'roles-detail'
        | 'roles-permissions'
        | 'roles-update'
      views:
        | 'default'
      pathParamNames:
        | 'roleId'
    }
    'src/routes/settings/roles/[roleId]/edit.route.vue': {
      routes:
        | 'roles-update'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/settings/roles/[roleId]/permissions/index.route.vue': {
      routes:
        | 'roles-permissions'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
