import scope0 from "/Users/gamer/Documents/projects/carta/apps/api/src/routes/(authenticated)/+scope.ts"
import scope1 from "/Users/gamer/Documents/projects/carta/apps/api/src/routes/(authenticated)/permissions/+scope.ts"
import scope2 from "/Users/gamer/Documents/projects/carta/apps/api/src/routes/(authenticated)/roles/+scope.ts"
import scope4 from "/Users/gamer/Documents/projects/carta/apps/api/src/routes/(authenticated)/users/+scope.ts"
import scope5 from "/Users/gamer/Documents/projects/carta/apps/api/src/routes/+scope.ts"
import * as route0 from "/Users/gamer/Documents/projects/carta/apps/api/src/routes/api/auth/get-session/+server.ts"
import * as route1 from "/Users/gamer/Documents/projects/carta/apps/api/src/routes/api/auth/sign-in/email/+server.ts"
import * as route2 from "/Users/gamer/Documents/projects/carta/apps/api/src/routes/api/auth/sign-out/+server.ts"
import * as route3 from "/Users/gamer/Documents/projects/carta/apps/api/src/routes/(authenticated)/files/+server.ts"
import * as route4 from "/Users/gamer/Documents/projects/carta/apps/api/src/routes/(authenticated)/files/object/+server.ts"
import * as route5 from "/Users/gamer/Documents/projects/carta/apps/api/src/routes/(authenticated)/files/presigned-url/+server.ts"
import * as route6 from "/Users/gamer/Documents/projects/carta/apps/api/src/routes/health/+server.ts"
import * as route7 from "/Users/gamer/Documents/projects/carta/apps/api/src/routes/(authenticated)/me/+server.ts"
import * as route8 from "/Users/gamer/Documents/projects/carta/apps/api/src/routes/openapi.json/+server.ts"
import * as route9 from "/Users/gamer/Documents/projects/carta/apps/api/src/routes/(authenticated)/permissions/detail/[id]/+server.ts"
import * as route10 from "/Users/gamer/Documents/projects/carta/apps/api/src/routes/(authenticated)/permissions/list/+server.ts"
import * as route11 from "/Users/gamer/Documents/projects/carta/apps/api/src/routes/(authenticated)/roles/create/+server.ts"
import * as route12 from "/Users/gamer/Documents/projects/carta/apps/api/src/routes/(authenticated)/roles/delete/[id]/+server.ts"
import * as route13 from "/Users/gamer/Documents/projects/carta/apps/api/src/routes/(authenticated)/roles/detail/[id]/+server.ts"
import * as route14 from "/Users/gamer/Documents/projects/carta/apps/api/src/routes/(authenticated)/roles/list/+server.ts"
import * as route15 from "/Users/gamer/Documents/projects/carta/apps/api/src/routes/(authenticated)/roles/update/[id]/+server.ts"
import * as route20 from "/Users/gamer/Documents/projects/carta/apps/api/src/routes/(authenticated)/users/create/+server.ts"
import * as route21 from "/Users/gamer/Documents/projects/carta/apps/api/src/routes/(authenticated)/users/detail/[id]/+server.ts"
import * as route22 from "/Users/gamer/Documents/projects/carta/apps/api/src/routes/(authenticated)/users/list/+server.ts"
import * as route23 from "/Users/gamer/Documents/projects/carta/apps/api/src/routes/(authenticated)/users/update/[id]/+server.ts"
import * as route24 from "/Users/gamer/Documents/projects/carta/apps/api/src/routes/(authenticated)/roles/[roleId]/permissions/+server.ts"
import * as route25 from "/Users/gamer/Documents/projects/carta/apps/api/src/routes/(authenticated)/roles/[roleId]/permissions/[permissionId]/+server.ts"
import * as route33 from "/Users/gamer/Documents/projects/carta/apps/api/src/routes/(authenticated)/users/[userId]/role-assignments/+server.ts"
import * as route34 from "/Users/gamer/Documents/projects/carta/apps/api/src/routes/(authenticated)/users/[userId]/role-assignments/[roleId]/+server.ts"