/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    'dashboard': RouteRecordInfo<
      'dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'master-data': RouteRecordInfo<
      'master-data',
      '/master-data',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'master-data-business-categories': RouteRecordInfo<
      'master-data-business-categories',
      '/master-data/business-categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'master-data-business-categories-detail': RouteRecordInfo<
      'master-data-business-categories-detail',
      '/master-data/business-categories/:businessCategoryId/detail',
      { businessCategoryId: ParamValue<true> },
      { businessCategoryId: ParamValue<false> },
      | never
    >,
    'master-data-business-categories-edit': RouteRecordInfo<
      'master-data-business-categories-edit',
      '/master-data/business-categories/:businessCategoryId/edit',
      { businessCategoryId: ParamValue<true> },
      { businessCategoryId: ParamValue<false> },
      | never
    >,
    'master-data-business-categories-create': RouteRecordInfo<
      'master-data-business-categories-create',
      '/master-data/business-categories/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'master-data-divisions': RouteRecordInfo<
      'master-data-divisions',
      '/master-data/divisions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'master-data-divisions-detail': RouteRecordInfo<
      'master-data-divisions-detail',
      '/master-data/divisions/:divisionId/detail',
      { divisionId: ParamValue<true> },
      { divisionId: ParamValue<false> },
      | never
    >,
    'master-data-divisions-edit': RouteRecordInfo<
      'master-data-divisions-edit',
      '/master-data/divisions/:divisionId/edit',
      { divisionId: ParamValue<true> },
      { divisionId: ParamValue<false> },
      | never
    >,
    'master-data-divisions-create': RouteRecordInfo<
      'master-data-divisions-create',
      '/master-data/divisions/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'master-data-number-configs': RouteRecordInfo<
      'master-data-number-configs',
      '/master-data/number-configs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'master-data-number-configs-detail': RouteRecordInfo<
      'master-data-number-configs-detail',
      '/master-data/number-configs/:numberConfigId/detail',
      { numberConfigId: ParamValue<true> },
      { numberConfigId: ParamValue<false> },
      | never
    >,
    'master-data-number-configs-edit': RouteRecordInfo<
      'master-data-number-configs-edit',
      '/master-data/number-configs/:numberConfigId/edit',
      { numberConfigId: ParamValue<true> },
      { numberConfigId: ParamValue<false> },
      | never
    >,
    'master-data-number-configs-create': RouteRecordInfo<
      'master-data-number-configs-create',
      '/master-data/number-configs/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'master-data-number-variables': RouteRecordInfo<
      'master-data-number-variables',
      '/master-data/number-variables',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'master-data-number-variables-detail': RouteRecordInfo<
      'master-data-number-variables-detail',
      '/master-data/number-variables/:numberVariableId/detail',
      { numberVariableId: ParamValue<true> },
      { numberVariableId: ParamValue<false> },
      | never
    >,
    'master-data-projects': RouteRecordInfo<
      'master-data-projects',
      '/master-data/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'master-data-projects-detail': RouteRecordInfo<
      'master-data-projects-detail',
      '/master-data/projects/:projectId/detail',
      { projectId: ParamValue<true> },
      { projectId: ParamValue<false> },
      | 'master-data-projects-detail-vendors'
      | 'master-data-projects-detail-vendors-create'
      | 'master-data-projects-detail-vendors-detail'
      | 'master-data-projects-detail-vendors-edit'
    >,
    'master-data-projects-detail-vendors': RouteRecordInfo<
      'master-data-projects-detail-vendors',
      '/master-data/projects/:projectId/detail/vendors',
      { projectId: ParamValue<true> },
      { projectId: ParamValue<false> },
      | never
    >,
    'master-data-projects-detail-vendors-detail': RouteRecordInfo<
      'master-data-projects-detail-vendors-detail',
      '/master-data/projects/:projectId/detail/vendors/:projectVendorId/detail',
      { projectId: ParamValue<true>, projectVendorId: ParamValue<true> },
      { projectId: ParamValue<false>, projectVendorId: ParamValue<false> },
      | never
    >,
    'master-data-projects-detail-vendors-edit': RouteRecordInfo<
      'master-data-projects-detail-vendors-edit',
      '/master-data/projects/:projectId/detail/vendors/:projectVendorId/edit',
      { projectId: ParamValue<true>, projectVendorId: ParamValue<true> },
      { projectId: ParamValue<false>, projectVendorId: ParamValue<false> },
      | never
    >,
    'master-data-projects-detail-vendors-create': RouteRecordInfo<
      'master-data-projects-detail-vendors-create',
      '/master-data/projects/:projectId/detail/vendors/create',
      { projectId: ParamValue<true> },
      { projectId: ParamValue<false> },
      | never
    >,
    'master-data-projects-edit': RouteRecordInfo<
      'master-data-projects-edit',
      '/master-data/projects/:projectId/edit',
      { projectId: ParamValue<true> },
      { projectId: ParamValue<false> },
      | never
    >,
    'master-data-projects-create': RouteRecordInfo<
      'master-data-projects-create',
      '/master-data/projects/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'master-data-pts-work-categories': RouteRecordInfo<
      'master-data-pts-work-categories',
      '/master-data/pts-work-categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'master-data-pts-work-categories-detail': RouteRecordInfo<
      'master-data-pts-work-categories-detail',
      '/master-data/pts-work-categories/:ptsWorkCategoryId/detail',
      { ptsWorkCategoryId: ParamValue<true> },
      { ptsWorkCategoryId: ParamValue<false> },
      | never
    >,
    'master-data-pts-work-categories-edit': RouteRecordInfo<
      'master-data-pts-work-categories-edit',
      '/master-data/pts-work-categories/:ptsWorkCategoryId/edit',
      { ptsWorkCategoryId: ParamValue<true> },
      { ptsWorkCategoryId: ParamValue<false> },
      | never
    >,
    'master-data-pts-work-categories-create': RouteRecordInfo<
      'master-data-pts-work-categories-create',
      '/master-data/pts-work-categories/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'master-data-root-causes': RouteRecordInfo<
      'master-data-root-causes',
      '/master-data/root-causes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'master-data-root-causes-detail': RouteRecordInfo<
      'master-data-root-causes-detail',
      '/master-data/root-causes/:rootCauseId/detail',
      { rootCauseId: ParamValue<true> },
      { rootCauseId: ParamValue<false> },
      | never
    >,
    'master-data-root-causes-edit': RouteRecordInfo<
      'master-data-root-causes-edit',
      '/master-data/root-causes/:rootCauseId/edit',
      { rootCauseId: ParamValue<true> },
      { rootCauseId: ParamValue<false> },
      | never
    >,
    'master-data-root-causes-create': RouteRecordInfo<
      'master-data-root-causes-create',
      '/master-data/root-causes/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'master-data-uoms': RouteRecordInfo<
      'master-data-uoms',
      '/master-data/uoms',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'master-data-uoms-detail': RouteRecordInfo<
      'master-data-uoms-detail',
      '/master-data/uoms/:uomId/detail',
      { uomId: ParamValue<true> },
      { uomId: ParamValue<false> },
      | never
    >,
    'master-data-uoms-edit': RouteRecordInfo<
      'master-data-uoms-edit',
      '/master-data/uoms/:uomId/edit',
      { uomId: ParamValue<true> },
      { uomId: ParamValue<false> },
      | never
    >,
    'master-data-uoms-create': RouteRecordInfo<
      'master-data-uoms-create',
      '/master-data/uoms/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'master-data-work-items': RouteRecordInfo<
      'master-data-work-items',
      '/master-data/work-items',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'notifications': RouteRecordInfo<
      'notifications',
      '/notifications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-permissions': RouteRecordInfo<
      'settings-permissions',
      '/settings/permissions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-permissions-detail': RouteRecordInfo<
      'settings-permissions-detail',
      '/settings/permissions/:permissionId/detail',
      { permissionId: ParamValue<true> },
      { permissionId: ParamValue<false> },
      | never
    >,
    'settings-roles': RouteRecordInfo<
      'settings-roles',
      '/settings/roles',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-roles-detail': RouteRecordInfo<
      'settings-roles-detail',
      '/settings/roles/:roleId/detail',
      { roleId: ParamValue<true> },
      { roleId: ParamValue<false> },
      | 'settings-roles-detail-permissions'
    >,
    'settings-roles-detail-permissions': RouteRecordInfo<
      'settings-roles-detail-permissions',
      '/settings/roles/:roleId/detail/permissions',
      { roleId: ParamValue<true> },
      { roleId: ParamValue<false> },
      | never
    >,
    'settings-roles-edit': RouteRecordInfo<
      'settings-roles-edit',
      '/settings/roles/:roleId/edit',
      { roleId: ParamValue<true> },
      { roleId: ParamValue<false> },
      | never
    >,
    'settings-roles-create': RouteRecordInfo<
      'settings-roles-create',
      '/settings/roles/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-users': RouteRecordInfo<
      'settings-users',
      '/settings/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-users-detail': RouteRecordInfo<
      'settings-users-detail',
      '/settings/users/:userId/detail',
      { userId: ParamValue<true> },
      { userId: ParamValue<false> },
      | 'settings-users-detail-project-roles'
      | 'settings-users-detail-system-roles'
    >,
    'settings-users-detail-project-roles': RouteRecordInfo<
      'settings-users-detail-project-roles',
      '/settings/users/:userId/detail/project-roles',
      { userId: ParamValue<true> },
      { userId: ParamValue<false> },
      | never
    >,
    'settings-users-detail-system-roles': RouteRecordInfo<
      'settings-users-detail-system-roles',
      '/settings/users/:userId/detail/system-roles',
      { userId: ParamValue<true> },
      { userId: ParamValue<false> },
      | never
    >,
    'settings-users-edit': RouteRecordInfo<
      'settings-users-edit',
      '/settings/users/:userId/edit',
      { userId: ParamValue<true> },
      { userId: ParamValue<false> },
      | never
    >,
    'settings-users-create': RouteRecordInfo<
      'settings-users-create',
      '/settings/users/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'to-do': RouteRecordInfo<
      'to-do',
      '/to-do',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'input-catalog': RouteRecordInfo<
      'input-catalog',
      '/input-catalog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'auth-login': RouteRecordInfo<
      'auth-login',
      '/auth/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'privacy-policy': RouteRecordInfo<
      'privacy-policy',
      '/privacy-policy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'not-found': RouteRecordInfo<
      'not-found',
      '/:path(.*)',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/routes/(authenticated)/authenticated.layout.vue': {
      routes:
        | 'dashboard'
        | 'master-data'
        | 'master-data-business-categories'
        | 'master-data-business-categories-create'
        | 'master-data-business-categories-detail'
        | 'master-data-business-categories-edit'
        | 'master-data-divisions'
        | 'master-data-divisions-create'
        | 'master-data-divisions-detail'
        | 'master-data-divisions-edit'
        | 'master-data-number-configs'
        | 'master-data-number-configs-create'
        | 'master-data-number-configs-detail'
        | 'master-data-number-configs-edit'
        | 'master-data-number-variables'
        | 'master-data-number-variables-detail'
        | 'master-data-projects'
        | 'master-data-projects-create'
        | 'master-data-projects-detail'
        | 'master-data-projects-detail-vendors'
        | 'master-data-projects-detail-vendors-create'
        | 'master-data-projects-detail-vendors-detail'
        | 'master-data-projects-detail-vendors-edit'
        | 'master-data-projects-edit'
        | 'master-data-pts-work-categories'
        | 'master-data-pts-work-categories-create'
        | 'master-data-pts-work-categories-detail'
        | 'master-data-pts-work-categories-edit'
        | 'master-data-root-causes'
        | 'master-data-root-causes-create'
        | 'master-data-root-causes-detail'
        | 'master-data-root-causes-edit'
        | 'master-data-uoms'
        | 'master-data-uoms-create'
        | 'master-data-uoms-detail'
        | 'master-data-uoms-edit'
        | 'master-data-work-items'
        | 'notifications'
        | 'settings-permissions'
        | 'settings-permissions-detail'
        | 'settings-roles'
        | 'settings-roles-create'
        | 'settings-roles-detail'
        | 'settings-roles-detail-permissions'
        | 'settings-roles-edit'
        | 'settings-users'
        | 'settings-users-create'
        | 'settings-users-detail'
        | 'settings-users-detail-project-roles'
        | 'settings-users-detail-system-roles'
        | 'settings-users-edit'
        | 'to-do'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/dashboard/index.route.vue': {
      routes:
        | 'dashboard'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/master-data/index.route.vue': {
      routes:
        | 'master-data'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/master-data/business-categories/index.route.vue': {
      routes:
        | 'master-data-business-categories'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/master-data/business-categories/[businessCategoryId]/detail.route.vue': {
      routes:
        | 'master-data-business-categories-detail'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/master-data/business-categories/[businessCategoryId]/edit.route.vue': {
      routes:
        | 'master-data-business-categories-edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/master-data/business-categories/create.route.vue': {
      routes:
        | 'master-data-business-categories-create'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/master-data/divisions/index.route.vue': {
      routes:
        | 'master-data-divisions'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/master-data/divisions/[divisionId]/detail.route.vue': {
      routes:
        | 'master-data-divisions-detail'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/master-data/divisions/[divisionId]/edit.route.vue': {
      routes:
        | 'master-data-divisions-edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/master-data/divisions/create.route.vue': {
      routes:
        | 'master-data-divisions-create'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/master-data/number-configs/index.route.vue': {
      routes:
        | 'master-data-number-configs'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/master-data/number-configs/[numberConfigId]/detail.route.vue': {
      routes:
        | 'master-data-number-configs-detail'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/master-data/number-configs/[numberConfigId]/edit.route.vue': {
      routes:
        | 'master-data-number-configs-edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/master-data/number-configs/create.route.vue': {
      routes:
        | 'master-data-number-configs-create'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/master-data/number-variables/index.route.vue': {
      routes:
        | 'master-data-number-variables'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/master-data/number-variables/[numberVariableId]/detail.route.vue': {
      routes:
        | 'master-data-number-variables-detail'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/master-data/projects/index.route.vue': {
      routes:
        | 'master-data-projects'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/master-data/projects/[projectId]/detail.route.vue': {
      routes:
        | 'master-data-projects-detail'
        | 'master-data-projects-detail-vendors'
        | 'master-data-projects-detail-vendors-create'
        | 'master-data-projects-detail-vendors-detail'
        | 'master-data-projects-detail-vendors-edit'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/master-data/projects/[projectId]/detail/vendors/index.route.vue': {
      routes:
        | 'master-data-projects-detail-vendors'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/master-data/projects/[projectId]/detail/vendors/[projectVendorId]/detail.route.vue': {
      routes:
        | 'master-data-projects-detail-vendors-detail'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/master-data/projects/[projectId]/detail/vendors/[projectVendorId]/edit.route.vue': {
      routes:
        | 'master-data-projects-detail-vendors-edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/master-data/projects/[projectId]/detail/vendors/create.route.vue': {
      routes:
        | 'master-data-projects-detail-vendors-create'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/master-data/projects/[projectId]/edit.route.vue': {
      routes:
        | 'master-data-projects-edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/master-data/projects/create.route.vue': {
      routes:
        | 'master-data-projects-create'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/master-data/pts-work-categories/index.route.vue': {
      routes:
        | 'master-data-pts-work-categories'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/master-data/pts-work-categories/[ptsWorkCategoryId]/detail.route.vue': {
      routes:
        | 'master-data-pts-work-categories-detail'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/master-data/pts-work-categories/[ptsWorkCategoryId]/edit.route.vue': {
      routes:
        | 'master-data-pts-work-categories-edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/master-data/pts-work-categories/create.route.vue': {
      routes:
        | 'master-data-pts-work-categories-create'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/master-data/root-causes/index.route.vue': {
      routes:
        | 'master-data-root-causes'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/master-data/root-causes/[rootCauseId]/detail.route.vue': {
      routes:
        | 'master-data-root-causes-detail'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/master-data/root-causes/[rootCauseId]/edit.route.vue': {
      routes:
        | 'master-data-root-causes-edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/master-data/root-causes/create.route.vue': {
      routes:
        | 'master-data-root-causes-create'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/master-data/uoms/index.route.vue': {
      routes:
        | 'master-data-uoms'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/master-data/uoms/[uomId]/detail.route.vue': {
      routes:
        | 'master-data-uoms-detail'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/master-data/uoms/[uomId]/edit.route.vue': {
      routes:
        | 'master-data-uoms-edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/master-data/uoms/create.route.vue': {
      routes:
        | 'master-data-uoms-create'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/master-data/work-items/index.route.vue': {
      routes:
        | 'master-data-work-items'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/notifications/index.route.vue': {
      routes:
        | 'notifications'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/settings/permissions/index.route.vue': {
      routes:
        | 'settings-permissions'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/settings/permissions/[permissionId]/detail.route.vue': {
      routes:
        | 'settings-permissions-detail'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/settings/roles/index.route.vue': {
      routes:
        | 'settings-roles'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/settings/roles/[roleId]/detail.route.vue': {
      routes:
        | 'settings-roles-detail'
        | 'settings-roles-detail-permissions'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/settings/roles/[roleId]/detail/permissions/index.route.vue': {
      routes:
        | 'settings-roles-detail-permissions'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/settings/roles/[roleId]/edit.route.vue': {
      routes:
        | 'settings-roles-edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/settings/roles/create.route.vue': {
      routes:
        | 'settings-roles-create'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/settings/users/index.route.vue': {
      routes:
        | 'settings-users'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/settings/users/[userId]/detail.route.vue': {
      routes:
        | 'settings-users-detail'
        | 'settings-users-detail-project-roles'
        | 'settings-users-detail-system-roles'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/settings/users/[userId]/detail/project-roles/index.route.vue': {
      routes:
        | 'settings-users-detail-project-roles'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/settings/users/[userId]/detail/system-roles/index.route.vue': {
      routes:
        | 'settings-users-detail-system-roles'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/settings/users/[userId]/edit.route.vue': {
      routes:
        | 'settings-users-edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/settings/users/create.route.vue': {
      routes:
        | 'settings-users-create'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/to-do/index.route.vue': {
      routes:
        | 'to-do'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(demo)/demo.layout.vue': {
      routes:
        | 'input-catalog'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/routes/(demo)/input-catalog/index.route.vue': {
      routes:
        | 'input-catalog'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(public)/public.layout.vue': {
      routes:
        | 'auth-login'
        | 'privacy-policy'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/routes/(public)/auth/login/index.route.vue': {
      routes:
        | 'auth-login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(public)/privacy-policy/index.route.vue': {
      routes:
        | 'privacy-policy'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/not-found.route.vue': {
      routes:
        | 'not-found'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
