/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    'dashboard': RouteRecordInfo<
      'dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'hr-overtimes': RouteRecordInfo<
      'hr-overtimes',
      '/hr/overtimes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'hr-overtimes-detail': RouteRecordInfo<
      'hr-overtimes-detail',
      '/hr/overtimes/:overtimeId/detail',
      { overtimeId: ParamValue<true> },
      { overtimeId: ParamValue<false> },
      | never
    >,
    'hr-overtimes-edit': RouteRecordInfo<
      'hr-overtimes-edit',
      '/hr/overtimes/:overtimeId/edit',
      { overtimeId: ParamValue<true> },
      { overtimeId: ParamValue<false> },
      | never
    >,
    'hr-overtimes-create': RouteRecordInfo<
      'hr-overtimes-create',
      '/hr/overtimes/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-roles': RouteRecordInfo<
      'settings-roles',
      '/settings/roles',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-roles-detail': RouteRecordInfo<
      'settings-roles-detail',
      '/settings/roles/:roleId/detail',
      { roleId: ParamValue<true> },
      { roleId: ParamValue<false> },
      | 'settings-roles-detail-permissions'
    >,
    'settings-roles-detail-permissions': RouteRecordInfo<
      'settings-roles-detail-permissions',
      '/settings/roles/:roleId/detail/permissions',
      { roleId: ParamValue<true> },
      { roleId: ParamValue<false> },
      | never
    >,
    'settings-roles-edit': RouteRecordInfo<
      'settings-roles-edit',
      '/settings/roles/:roleId/edit',
      { roleId: ParamValue<true> },
      { roleId: ParamValue<false> },
      | never
    >,
    'settings-roles-create': RouteRecordInfo<
      'settings-roles-create',
      '/settings/roles/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-users': RouteRecordInfo<
      'settings-users',
      '/settings/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-users-detail': RouteRecordInfo<
      'settings-users-detail',
      '/settings/users/:userId/detail',
      { userId: ParamValue<true> },
      { userId: ParamValue<false> },
      | 'settings-users-detail-roles'
    >,
    'settings-users-detail-roles': RouteRecordInfo<
      'settings-users-detail-roles',
      '/settings/users/:userId/detail/roles',
      { userId: ParamValue<true> },
      { userId: ParamValue<false> },
      | never
    >,
    'settings-users-edit': RouteRecordInfo<
      'settings-users-edit',
      '/settings/users/:userId/edit',
      { userId: ParamValue<true> },
      { userId: ParamValue<false> },
      | never
    >,
    'to-do': RouteRecordInfo<
      'to-do',
      '/to-do',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'input-catalog': RouteRecordInfo<
      'input-catalog',
      '/input-catalog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'auth-login': RouteRecordInfo<
      'auth-login',
      '/auth/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'privacy-policy': RouteRecordInfo<
      'privacy-policy',
      '/privacy-policy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'not-found': RouteRecordInfo<
      'not-found',
      '/:path(.*)',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/routes/(authenticated)/authenticated.layout.vue': {
      routes:
        | 'dashboard'
        | 'hr-overtimes'
        | 'hr-overtimes-create'
        | 'hr-overtimes-detail'
        | 'hr-overtimes-edit'
        | 'settings-roles'
        | 'settings-roles-create'
        | 'settings-roles-detail'
        | 'settings-roles-detail-permissions'
        | 'settings-roles-edit'
        | 'settings-users'
        | 'settings-users-detail'
        | 'settings-users-detail-roles'
        | 'settings-users-edit'
        | 'to-do'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/dashboard/index.route.vue': {
      routes:
        | 'dashboard'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/hr/overtimes/index.route.vue': {
      routes:
        | 'hr-overtimes'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/hr/overtimes/[overtimeId]/detail.route.vue': {
      routes:
        | 'hr-overtimes-detail'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/hr/overtimes/[overtimeId]/edit.route.vue': {
      routes:
        | 'hr-overtimes-edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/hr/overtimes/create.route.vue': {
      routes:
        | 'hr-overtimes-create'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/settings/roles/index.route.vue': {
      routes:
        | 'settings-roles'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/settings/roles/[roleId]/detail.route.vue': {
      routes:
        | 'settings-roles-detail'
        | 'settings-roles-detail-permissions'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/settings/roles/[roleId]/detail/permissions/index.route.vue': {
      routes:
        | 'settings-roles-detail-permissions'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/settings/roles/[roleId]/edit.route.vue': {
      routes:
        | 'settings-roles-edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/settings/roles/create.route.vue': {
      routes:
        | 'settings-roles-create'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/settings/users/index.route.vue': {
      routes:
        | 'settings-users'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/settings/users/[userId]/detail.route.vue': {
      routes:
        | 'settings-users-detail'
        | 'settings-users-detail-roles'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/settings/users/[userId]/detail/roles/index.route.vue': {
      routes:
        | 'settings-users-detail-roles'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/settings/users/[userId]/edit.route.vue': {
      routes:
        | 'settings-users-edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/to-do/index.route.vue': {
      routes:
        | 'to-do'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(demo)/demo.layout.vue': {
      routes:
        | 'input-catalog'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/routes/(demo)/input-catalog/index.route.vue': {
      routes:
        | 'input-catalog'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(public)/public.layout.vue': {
      routes:
        | 'auth-login'
        | 'privacy-policy'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/routes/(public)/auth/login/index.route.vue': {
      routes:
        | 'auth-login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(public)/privacy-policy/index.route.vue': {
      routes:
        | 'privacy-policy'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/not-found.route.vue': {
      routes:
        | 'not-found'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
