/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    'organizations-users-detail': RouteRecordInfo<
      'organizations-users-detail',
      '/organizations/:organizationId/users/:userId/detail',
      { organizationId: ParamValue<true>, userId: ParamValue<true> },
      { organizationId: ParamValue<false>, userId: ParamValue<false> },
      | never
    >,
    'settings-roles': RouteRecordInfo<
      'settings-roles',
      '/settings/roles',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-roles-detail': RouteRecordInfo<
      'settings-roles-detail',
      '/settings/roles/:roleId/detail',
      { roleId: ParamValue<true> },
      { roleId: ParamValue<false> },
      | 'settings-roles-detail-permissions'
    >,
    'settings-roles-detail-permissions': RouteRecordInfo<
      'settings-roles-detail-permissions',
      '/settings/roles/:roleId/detail/permissions',
      { roleId: ParamValue<true> },
      { roleId: ParamValue<false> },
      | never
    >,
    'settings-roles-edit': RouteRecordInfo<
      'settings-roles-edit',
      '/settings/roles/:roleId/edit',
      { roleId: ParamValue<true> },
      { roleId: ParamValue<false> },
      | never
    >,
    'settings-roles-new': RouteRecordInfo<
      'settings-roles-new',
      '/settings/roles/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'not-found': RouteRecordInfo<
      'not-found',
      '/:path(.*)',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/routes/(authenticated)/authenticated.layout.vue': {
      routes:
        | 'organizations-users-detail'
        | 'settings-roles'
        | 'settings-roles-detail'
        | 'settings-roles-detail-permissions'
        | 'settings-roles-edit'
        | 'settings-roles-new'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/organizations/[organizationId]/users/[userId]/detail.route.vue': {
      routes:
        | 'organizations-users-detail'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/settings/roles/index.route.vue': {
      routes:
        | 'settings-roles'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/settings/roles/[roleId]/detail.route.vue': {
      routes:
        | 'settings-roles-detail'
        | 'settings-roles-detail-permissions'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/settings/roles/[roleId]/detail/permissions/index.route.vue': {
      routes:
        | 'settings-roles-detail-permissions'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/settings/roles/[roleId]/edit.route.vue': {
      routes:
        | 'settings-roles-edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/settings/roles/new.route.vue': {
      routes:
        | 'settings-roles-new'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/not-found.route.vue': {
      routes:
        | 'not-found'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
