/* eslint-disable */
// This file is generated by scripts/generate-rpc.ts. Do not edit.

import type { Hono } from 'hono'
import type { z } from 'zod/v4'
import type { CustomRoutesSchema } from '@southneuhof/sprindle/routes'
import type { routes } from './routes'
import type * as ProductsEntityModule from './domains/products/product.entity'

type ListQuery = {
  page?: string
  limit?: string
  search?: string
}

type JsonEndpoint<TInput, TStatus extends number = 200> = {
  input: TInput
  output: unknown
  outputFormat: 'json'
  status: TStatus
}

export type ModelRpcSchema = {
  '/products/create': {
    '$post': JsonEndpoint<{ json: z.input<typeof ProductsEntityModule.product.schemas.create> }, 201>
  }
  '/products/customProductAction': {
    '$post': JsonEndpoint<{}, 200>
  }
  '/products/customProductMaterialize': {
    '$get': JsonEndpoint<{}, 200>
  }
  '/products/delete/:id': {
    '$delete': JsonEndpoint<{ param: { id: string } }, 200>
  }
  '/products/detail/:id': {
    '$get': JsonEndpoint<{ param: { id: string } }, 200>
  }
  '/products/list': {
    '$get': JsonEndpoint<{ query: ListQuery }, 200>
  }
  '/products/nested/test/versionTest': {
    '$get': JsonEndpoint<{}, 200>
  }
  '/products/nested/version1': {
    '$get': JsonEndpoint<{}, 200>
  }
  '/products/update/:id': {
    '$patch': JsonEndpoint<{ json: z.input<typeof ProductsEntityModule.product.schemas.update> } & { param: { id: string } }, 200>
  }
}

export type RpcSchema = ModelRpcSchema & CustomRoutesSchema<typeof routes>

export type AppType = Hono<{}, RpcSchema>
