/* eslint-disable */
// This file is generated by scripts/generate-rpc.ts. Do not edit.

import type { Hono } from 'hono'
import type { z } from 'zod/v4'
import type { product as ProductsEntity } from './domains/products/product.entity'

type ListQuery = {
  page?: string
  limit?: string
  search?: string
}

type JsonEndpoint<TInput, TStatus extends number = 200> = {
  input: TInput
  output: unknown
  outputFormat: 'json'
  status: TStatus
}

export type RpcSchema = {
  '/products/create': {
    '$post': JsonEndpoint<{ json: z.input<typeof ProductsEntity.schemas.create> }, 201>
  }
  '/products/customProductAction': {
    '$post': JsonEndpoint<{}, 200>
  }
  '/products/customProductMaterialize': {
    '$get': JsonEndpoint<{}, 200>
  }
  '/products/delete/:id': {
    '$delete': JsonEndpoint<{ param: { id: string } }, 200>
  }
  '/products/detail/:id': {
    '$get': JsonEndpoint<{ param: { id: string } }, 200>
  }
  '/products/list': {
    '$get': JsonEndpoint<{ query: ListQuery }, 200>
  }
  '/products/nested/test/versionTest': {
    '$get': JsonEndpoint<{}, 200>
  }
  '/products/nested/version1': {
    '$get': JsonEndpoint<{}, 200>
  }
  '/products/update/:id': {
    '$patch': JsonEndpoint<{ json: z.input<typeof ProductsEntity.schemas.update> } & { param: { id: string } }, 200>
  }
}

export type AppType = Hono<{}, RpcSchema>
