import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { activeNavigationModule, matchesNavigationPath, navigation, visibleNavigation } from '../navigation'
import { permissionByCode } from '../../../../api/src/authorization/catalog'

const srcRoot = join(dirname(fileURLToPath(import.meta.url)), '../..')

/** Route names generated by unplugin-vue-router — the mechanical source of truth. */
function generatedRouteNames(): Set<string> {
  const source = readFileSync(join(srcRoot, 'route-map.d.ts'), 'utf8')
  return new Set([...source.matchAll(/'([a-z0-9-]+)': RouteRecordInfo</g)].map((match) => match[1]!))
}

describe('navigation entrypoints', () => {
  it('keeps every entrypoint on a generated route', () => {
    const names = generatedRouteNames()
    const targets: string[] = []
    for (const module of navigation) {
      expect(module.routes.length).toBeGreaterThan(0)
      for (const entry of module.routes) {
        if ('separator' in entry || !('to' in entry)) continue
        targets.push(entry.to.name)
      }
    }
    expect(targets.filter((name) => !names.has(name))).toEqual([])
    expect(targets.length).toBeGreaterThan(0)
  })

  it('keeps dashboard and settings entrypoints with their grants', () => {
    const settings = navigation.find((module) => module.name === 'settings')!
    expect(settings.routes).toContainEqual({ to: { name: 'settings-users' }, permission: 'view-users', title: 'Users', icon: 'folder' })
    expect(settings.routes).toContainEqual({ to: { name: 'settings-roles' }, permission: 'view-roles', title: 'Roles', icon: 'folder' })
    expect(settings.routes).toContainEqual({ to: { name: 'settings-permissions' }, permission: 'view-permissions', title: 'Permissions', icon: 'folder' })
  })

  it('matches entrypoint subtrees at segment boundaries and prefers longest target', () => {
    const paths: Record<string, string> = {
      dashboard: '/dashboard',
      'settings-users': '/settings/users',
      'settings-roles': '/settings/roles',
    }
    const resolve = (to: unknown) => ({ path: paths[(to as { name: string }).name] ?? '/' })

    expect(activeNavigationModule('/settings/roles/7/detail', resolve, () => true)).toBe('settings')
    expect(activeNavigationModule('/settings/role', resolve, () => true)).toBeUndefined()
    expect(matchesNavigationPath('/settings/users/7/detail', '/settings/users')).toBe(true)
    expect(matchesNavigationPath('/settings/users-archived', '/settings/users')).toBe(false)
  })

  it('keeps only open menus visible without grants', () => {
    const visible = visibleNavigation(() => false)
    const routes = visible
      .flatMap((module) => module.routes)
      .filter((entry) => !('separator' in entry))
      .map((entry) => entry.name)

    expect(routes).toEqual(['dashboard'])
  })

  it('uses active catalog codes for every guarded entrypoint', () => {
    const codes: string[] = []
    for (const module of navigation) {
      for (const entry of module.routes) {
        if (!('separator' in entry) && 'permission' in entry && entry.permission !== null) codes.push(entry.permission)
      }
    }

    expect(codes.filter((code) => !(code in permissionByCode))).toEqual([])
    expect(codes.every((code) => permissionByCode[code as keyof typeof permissionByCode].permission.active)).toBe(true)
  })
})
