import { describe, expect, it } from 'vitest'
import { createMemoryHistory, createRouter } from 'vue-router'
import { routes } from 'vue-router/auto-routes'

const router = createRouter({ history: createMemoryHistory(), routes })

describe('mechanical file routes', () => {
  it('marks generated authenticated routes and leaves public routes unmarked', () => {
    expect(router.resolve('/dashboard').meta.requiresAuth).toBe(true)
    expect(router.resolve('/settings/users').meta.requiresAuth).toBe(true)
    expect(router.resolve('/auth/login').meta.requiresAuth).not.toBe(true)
  })

  it('uses static segment names and detail parents', () => {
    expect(router.resolve({ name: 'settings-roles' }).path).toBe('/settings/roles')
    expect(router.resolve('/settings/roles/7/detail').name).toBe('settings-roles-detail')
    expect(router.resolve('/settings/roles/7/detail/permissions').name).toBe('settings-roles-detail-permissions')
    expect(router.resolve('/settings/permissions').name).toBe('settings-permissions')
    expect(router.resolve('/settings/permissions/7/detail').name).toBe('settings-permissions-detail')
    expect(router.resolve('/settings/users/7/detail/system-roles').name).toBe('settings-users-detail-system-roles')
    expect(router.resolve('/settings/users/7/detail/project-roles').name).toBe('settings-users-detail-project-roles')
    const projectVendors = router.resolve('/master-data/projects/7/detail/vendors')
    expect(projectVendors.name).toBe('master-data-projects-detail-vendors')
    expect(projectVendors.matched.map((record) => record.name)).toContain('master-data-projects-detail')
    expect(router.resolve('/master-data/projects/7/detail/vendors/create').name).toBe('master-data-projects-detail-vendors-create')
    expect(router.resolve('/master-data/projects/7/detail/vendors/vendor-1/detail').name).toBe('master-data-projects-detail-vendors-detail')
    expect(router.resolve('/master-data/projects/7/detail/vendors/vendor-1/edit').name).toBe('master-data-projects-detail-vendors-edit')
    expect(router.resolve('/master-data/permit-work-types').name).toBe('master-data-permit-work-types')
    expect(router.resolve('/master-data/permit-work-types/create').name).toBe('master-data-permit-work-types-create')
    expect(router.resolve('/master-data/permit-work-types/7/detail').name).toBe('master-data-permit-work-types-detail')
    expect(router.resolve('/master-data/permit-work-types/7/edit').name).toBe('master-data-permit-work-types-edit')
    expect(router.resolve('/master-data/permit-danger-source').name).toBe('master-data-permit-danger-source')
    expect(router.resolve('/master-data/permit-danger-source/create').name).toBe('master-data-permit-danger-source-create')
    expect(router.resolve('/master-data/permit-danger-source/7/detail').name).toBe('master-data-permit-danger-source-detail')
    expect(router.resolve('/master-data/permit-danger-source/7/edit').name).toBe('master-data-permit-danger-source-edit')
    expect(router.resolve('/master-data/permit-attachment').name).toBe('master-data-permit-attachment')
    expect(router.resolve('/master-data/permit-attachment/create').name).toBe('master-data-permit-attachment-create')
    expect(router.resolve('/master-data/permit-attachment/7/detail').name).toBe('master-data-permit-attachment-detail')
    expect(router.resolve('/master-data/permit-attachment/7/edit').name).toBe('master-data-permit-attachment-edit')
    expect(router.resolve('/master-data/safety-checklist').name).toBe('master-data-safety-checklist')
    expect(router.resolve('/master-data/safety-checklist/create').name).toBe('master-data-safety-checklist-create')
    expect(router.resolve('/master-data/safety-checklist/7/detail').name).toBe('master-data-safety-checklist-detail')
    expect(router.resolve('/master-data/safety-checklist/7/edit').name).toBe('master-data-safety-checklist-edit')
    expect(router.resolve('/master-data/permit-category-apd').name).toBe('master-data-permit-category-apd')
    expect(router.resolve('/master-data/permit-category-apd/create').name).toBe('master-data-permit-category-apd-create')
    expect(router.resolve('/master-data/permit-category-apd/7/detail').name).toBe('master-data-permit-category-apd-detail')
    expect(router.resolve('/master-data/permit-category-apd/7/detail/apd').name).toBe('master-data-permit-category-apd-detail-apd')
    expect(router.resolve('/master-data/permit-category-apd/7/edit').name).toBe('master-data-permit-category-apd-edit')
    expect(router.resolve('/master-data/permit-category-apd/7/detail/apd/create').name).toBe('master-data-permit-category-apd-detail-apd-create')
    expect(router.resolve('/master-data/permit-category-apd/7/detail/apd/apd-1/detail').name).toBe('master-data-permit-category-apd-detail-apd-detail')
    expect(router.resolve('/master-data/permit-category-apd/7/detail/apd/apd-1/edit').name).toBe('master-data-permit-category-apd-detail-apd-edit')
    expect(router.resolve('/notifications').name).toBe('notifications')
    expect(router.resolve('/master-data/emergency-simulation-topics').name).toBe('master-data-emergency-simulation-topics')
    expect(router.resolve('/master-data/emergency-simulation-topics/create').name).toBe('master-data-emergency-simulation-topics-create')
    expect(router.resolve('/master-data/emergency-simulation-topics/7/detail').name).toBe('master-data-emergency-simulation-topics-detail')
    expect(router.resolve('/master-data/emergency-simulation-topics/7/edit').name).toBe('master-data-emergency-simulation-topics-edit')
  })

  it('rejects removed bare detail URLs', () => {
    expect(router.resolve('/settings/roles/7').name).toBe('not-found')
    expect(router.resolve('/settings/users/7/roles').name).toBe('not-found')
    const retiredRoleGroups = ['role', 'groups'].join('-')
    expect(router.resolve('/settings/' + retiredRoleGroups).name).toBe('not-found')
    expect(router.resolve('/settings/permissions/create').name).toBe('not-found')
    expect(router.resolve('/settings/permissions/7/edit').name).toBe('not-found')
    expect(router.resolve('/master-data/projects/7/vendors').name).toBe('not-found')
    expect(router.resolve('/master-data/project-vendors').name).toBe('not-found')
  })
})
