	"id" text PRIMARY KEY,
	"user_id" text NOT NULL,
	"scope_type" text NOT NULL,
	"scope_value" text
);
--> statement-breakpoint
	"id" text PRIMARY KEY,
	"number" text NOT NULL,
	"reporter_name" text NOT NULL,
	"division" text NOT NULL,
	"project" text NOT NULL,
	"occurred_on" text NOT NULL,
	"occurred_at" text NOT NULL,
	"observed" text NOT NULL,
	"work_type" text NOT NULL,
	"activity" text NOT NULL,
	"location" text NOT NULL,
	"description" text,
	"non_conformity_report" text,
	"documentation_photo" text NOT NULL,
	"work_permit" text,
	"work_method" text,
	"investigation_report" text,
	"final_document" text,
	"status_code" text DEFAULT 'open' NOT NULL,
	"workflow_step" text DEFAULT 'draft' NOT NULL,
	"incident_type" text,
	"category" text,
	"stop_duration" text,
	"investigation_required" boolean,
	"follow_up" text,
	"safety_result" text,
	"deleted" boolean DEFAULT false NOT NULL,
	"created_by_user_id" text NOT NULL,
	"submitted_by_user_id" text,
	"reviewed_by_user_id" text,
	"approved_by_user_id" text,
	"closed_by_user_id" text,
	"submitted_at" timestamp,
	"reviewed_at" timestamp,
	"approved_at" timestamp,
	"closed_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint