import type { LabelDictionary } from '@southneuhof/loom'

export const appLabels = {
  title: 'Judul',
  name: 'Name',
  fullName: 'Full name',
  username: 'Username',
  code: 'Code',
  email: 'Email',
  telephone: 'Telephone',
  description: 'Keterangan',
  active: 'Status',
  statusCode: 'Status',
  status: 'Status',
  createdAt: 'Dibuat',
  updatedAt: 'Diperbarui Pada',
  publishedAt: 'Diterbitkan Pada',
  date: 'Tanggal',
  startDate: 'Tanggal Mulai',
  endDate: 'Tanggal Selesai',
  year: 'Tahun',
  file: 'File',
  updatedBy: 'Diperbarui Oleh',
  createdBy: 'Dibuat Oleh',
  departmentId: 'Unit Kerja',
  number: 'Nomor',
  sectionName: 'Ruas',
  sectionId: 'Ruas',
  gateName: 'Gerbang',
  gateId: 'Gerbang',
  assetId: 'Asset',
  locationId: 'Location',
  startMonth: 'Periode Mulai',
  endMonth: 'Periode Selesai',
  approvalDescription: 'Keterangan',
  verificationDescription: 'Keterangan',
  submissionDescription: 'Keterangan',
  arrayApprovalAttachment: 'Lampiran',
  arrayVerificationAttachment: 'Lampiran',
  arraySubmissionAttachment: 'Lampiran',
  arrayClauses: 'Clauses',
} as const satisfies LabelDictionary
